// Import the action creators
import {
  setDateOfBirth,
  setFirstName,
  setGenderPreferences,
  setGender,
  setPictures,
  setEmail,
  setRelationshipGoal,
  setPhoneNumber,
  setShowLocationScreen,
  setIsRegisterCompleted,
  setProgressBarValue,
  setAdditionalInformation,
  setInterests,
  resetRegister,
  setUserProfile,
  editSetBio,
  editSetHeight,
  editSetAdditionalInformation,
  editSetGenderInformation,
  editSetJobTitle,
  editSetCompany,
  editSetSexualOrientation,
  editSetModalVisible,
  editSetLanguages,
  editInitUserProfile,
} from './actions';

import {Store, Persistor} from './store';

// Export the action creators
export {
  setDateOfBirth,
  setFirstName,
  setGenderPreferences,
  setGender,
  setPictures,
  setEmail,
  setRelationshipGoal,
  setPhoneNumber,
  Store,
  setShowLocationScreen,
  setIsRegisterCompleted,
  Persistor,
  setProgressBarValue,
  setAdditionalInformation,
  setInterests,
  resetRegister,
  setUserProfile,
  editSetBio,
  editSetHeight,
  editSetAdditionalInformation,
  editSetGenderInformation,
  editSetJobTitle,
  editSetCompany,
  editSetSexualOrientation,
  editSetModalVisible,
  editSetLanguages,
  editInitUserProfile,
};
