export const ROUTES = {
  // AUTH
  // Register
  REGISTER_NAVIGATOR: 'REGISTER_NAVIGATOR' as const,
  REGISTER_FIRST_NAME_SCREEN: 'REGISTER_FIRST_NAME_SCREEN' as const,
  REGISTER_DATE_OF_BIRTH_SCREEN: 'REGISTER_DATE_OF_BIRTH_SCREEN' as const,
  REGISTER_SEEKING_SCREEN: 'REGISTER_SEEKING_SCREEN' as const,
  REGISTER_GENDER_SELECTION_SCREEN: 'REGISTER_GENDER_SELECTION_SCREEN' as const,
  REGISTER_PICTURE_UPLOAD_SCREEN: 'REGISTER_PICTURE_UPLOAD_SCREEN' as const,
  REGISTER_RECOVERY_EMAIL_SCREEN: 'REGISTER_RECOVERY_EMAIL_SCREEN' as const,
  REGISTER_RELATIONSHIP_GOAL_SCREEN:
    'REGISTER_RELATIONSHIP_GOAL_SCREEN' as const,
  REGISTER_TERMS_AND_CONDITIONS_SCREEN:
    'REGISTER_TERMS_AND_CONDITIONS_SCREEN' as const,
  REGISTER_MULTIPLE_QUESTIONS_SCREEN:
    'REGISTER_MULTIPLE_QUESTIONS_SCREEN' as const,
  REGISTER_WELCOME_SCREEN: 'REGISTER_WELCOME_SCREEN' as const,
  REGISTER_INTEREST_SCREEN: 'REGISTER_INTEREST_SCREEN' as const,

  // Login
  LOGIN_NAVIGATOR: 'LOGIN_NAVIGATOR' as const,
  LOGIN_START_SCREEN: 'LOGIN_START_SCREEN' as const,
  LOGIN_OTP_SCREEN: 'LOGIN_OTP_SCREEN' as const,

  EMAIL_VERIFICATION_SCREEN: 'EMAIL_VERIFICATION_SCREEN' as const,
  LOCATION_SCREEN: 'LOCATION_SCREEN' as const,

  // Bottom tab navigator
  BOTTOM_TAB_NAVIGATOR: 'BOTTOM_TAB_NAVIGATOR' as const,

  // Profile
  PROFILE_NAVIGATOR: 'PROFILE_NAVIGATOR' as const,
  USER_PROFILE_SCREEN: 'USER_PROFILE_SCREEN' as const,
  PUBLIC_PROFILE_SCREEN: 'PUBLIC_PROFILE_SCREEN' as const,
  EDIT_PROFILE_SCREEN: 'EDIT_PROFILE_SCREEN' as const,
  EDIT_GENDER_SCREEN: 'EDIT_GENDER_SCREEN' as const,
  EDIT_SEXUAL_ORIENTATION_SCREEN: 'EDIT_SEXUAL_ORIENTATION_SCREEN' as const,
  EDIT_LANGUAGE_SCREEN: 'EDIT_LANGUAGE_SCREEN' as const,
  EDIT_JOB_TITLE_SCREEN: 'EDIT_JOB_TITLE_SCREEN' as const,
  EDIT_COMPANY_SCREEN: 'EDIT_COMPANY_SCREEN' as const,
  EDIT_VACCINE_SCREEN: 'EDIT_VACCINE_SCREEN' as const,
  EDIT_ETHNICITY_SCREEN: 'EDIT_ETHNICITY_SCREEN' as const,
};
